# WeatherShield Multi-Policy Monitor
# Monitors multiple policies at once for efficiency

name: weathershield-batch-monitor
version: "1.0.0"
description: "Batch monitoring of all active WeatherShield policies"

triggers:
  - id: daily_batch_check
    type: cron
    config:
      schedule: "0 0 * * *"  # Daily at midnight
      
  - id: manual_batch
    type: webhook
    config:
      path: /batch-check

inputs:
  contract_address:
    type: string
    description: "WeatherShield contract address"

actions:
  # Step 1: Get total policy count
  - id: get_policy_count
    name: "Get Policy Count"
    type: evm_read
    config:
      network: "{{env.NETWORK}}"
      contract_address: "{{inputs.contract_address}}"
      abi_path: "./artifacts/contracts/WeatherShield.sol/WeatherShield.json"
      function: "policyCounter"
      params: []
    outputs:
      count: "{{result}}"

  # Step 2: Iterate through policies and check each
  - id: check_all_policies
    name: "Check All Active Policies"
    type: compute
    depends_on: [get_policy_count]
    config:
      runtime: javascript
      code: |
        const policyCount = parseInt(actions.get_policy_count.outputs.count);
        const policiesToCheck = [];
        
        // Generate list of policy IDs to check
        for (let i = 0; i < policyCount; i++) {
          policiesToCheck.push(i);
        }
        
        return {
          policies: policiesToCheck,
          total: policyCount
        };
    outputs:
      policies: "{{result.policies}}"
      total: "{{result.total}}"

  # Step 3: For each unique location, fetch weather data
  - id: aggregate_locations
    name: "Aggregate Unique Locations"
    type: evm_multicall
    depends_on: [check_all_policies]
    config:
      network: "{{env.NETWORK}}"
      contract_address: "{{inputs.contract_address}}"
      calls:
        - function: "getPolicy"
          params: ["{{actions.check_all_policies.outputs.policies}}"]
      
  # Step 4: Process results and trigger claims
  - id: batch_process
    name: "Batch Process Claims"
    type: compute
    depends_on: [aggregate_locations]
    config:
      runtime: javascript
      code: |
        console.log("=== Batch Processing Complete ===");
        console.log(`Total policies checked: ${actions.check_all_policies.outputs.total}`);
        
        return {
          success: true,
          policiesChecked: actions.check_all_policies.outputs.total
        };

env:
  NETWORK: "sepolia"

outputs:
  policies_checked:
    value: "{{actions.check_all_policies.outputs.total}}"
    description: "Number of policies checked"
