# WeatherShield CRE Workflow
# Monitors weather and triggers insurance payouts

name: weathershield-monitor
version: "1.0.0"

triggers:
  - id: scheduled
    type: cron
    config:
      schedule: "0 */6 * * *"  # every 6 hours

inputs:
  contract_address:
    type: string
    default: "0x0988119B3526C21129E0254f5E8bd995Bed51F6D"
  location:
    type: string
    default: "40.7128,-74.0060"
  policy_id:
    type: uint256
  weather_type:
    type: uint8

actions:
  # get weather from open-meteo (free api)
  - id: fetch_weather
    type: http_request
    config:
      method: GET
      url: "https://api.open-meteo.com/v1/forecast"
      params:
        latitude: "{{split(inputs.location, ',')[0]}}"
        longitude: "{{split(inputs.location, ',')[1]}}"
        current: "temperature_2m,rain"
        daily: "temperature_2m_max,temperature_2m_min,precipitation_sum"
        timezone: "auto"
    outputs:
      temp: "{{response.current.temperature_2m}}"
      rain: "{{response.current.rain}}"
      daily_precip: "{{response.daily.precipitation_sum[0]}}"
      temp_max: "{{response.daily.temperature_2m_max[0]}}"
      temp_min: "{{response.daily.temperature_2m_min[0]}}"

  # transform to contract format
  - id: transform
    type: compute
    depends_on: [fetch_weather]
    config:
      runtime: javascript
      code: |
        const type = inputs.weather_type;
        let val;
        
        if (type === 0 || type === 1) {
          val = Math.round(actions.fetch_weather.outputs.daily_precip * 10);
        } else if (type === 2) {
          val = Math.round(actions.fetch_weather.outputs.temp_min * 10);
        } else {
          val = Math.round(actions.fetch_weather.outputs.temp_max * 10);
        }
        
        return { value: val };
    outputs:
      weather_value: "{{result.value}}"

  # update contract
  - id: update_chain
    type: evm_write
    depends_on: [transform]
    config:
      address: "{{inputs.contract_address}}"
      abi: "function updateWeatherData(string,int256)"
      method: updateWeatherData
      params:
        - "{{inputs.location}}"
        - "{{actions.transform.outputs.weather_value}}"

  # check if claimable
  - id: check_claim
    type: evm_read
    depends_on: [update_chain]
    config:
      address: "{{inputs.contract_address}}"
      abi: "function isPolicyClaimable(uint256) view returns (bool)"
      method: isPolicyClaimable
      params:
        - "{{inputs.policy_id}}"
    outputs:
      claimable: "{{result}}"

  # process claim if triggered
  - id: process_claim
    type: evm_write
    depends_on: [check_claim]
    condition: "{{actions.check_claim.outputs.claimable == true}}"
    config:
      address: "{{inputs.contract_address}}"
      abi: "function processClaim(uint256,int256)"
      method: processClaim
      params:
        - "{{inputs.policy_id}}"
        - "{{actions.transform.outputs.weather_value}}"
